resources:
  - operator.yaml
  - rabbitMqCluster.yaml
  - job.yaml
  - service.yaml

patches:
  - target:
      kind: Deployment
      name: rabbitmq-cluster-operator
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "0"
  - target:
      kind: RabbitmqCluster
      name: rabbitmq
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "1"
  - target:
      kind: Job
      name: create-queues
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "2"      
  - target:
      kind: Service
      name: rabbitmq-service
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "3"
