apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  replicas: 1
  additionalConfig: |
      loopback_users.guest = false
  auth:
    existingSecret: sealed-rabbitmq-auth
  persistence:
    storageClassName: "standard"
    storage: 1Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: ClusterIP
