services:
  - name: http-server
    namespace: shortner
    replicas: 1
    image: bhatvinay7/url-http-server:f95ebb3d5ab7f40b5d20812ee499ce2edcd3a375
    port: 80
    targetPort: 3001
    nodePort: 30036
    secretRef: http-server-sealed-secret
    dockersecretRef: docker-sealed-secret
