apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: nats-server
  namespace: shortner
spec:
  size: 1                
  version: "2.10.2"
  auth:
    clientsAuthSecret: sealed-nats-auth
  pod:
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "250m"
        memory: "256Mi"
  jetstream:
    enabled: false        
