services:
  - name: url-analytics
    namespace: shortner
    replicas: 1
    image: bhatvinay7/url-analytics:f95ebb3d5ab7f40b5d20812ee499ce2edcd3a375
    port: 80
    targetPort: 3006
    nodePort: 3038
    secretRef: urlshortner-analytics-sealed-secret
    dockersecretRef: docker-sealed-secret
