services:
  - name: url-converter
    namespace: shortner
    replicas: 1
    image: bhatvinay7/url-shorturl-converter:51ad780a6ce492def246f5e4517a9cf89e6be12d
    port: 80
    targetPort: 3011
    nodePort: 30037
    secretRef: url-converter-sealed-secret
    dockersecretRef: docker-sealed-secret
