services:
  - name: url-converter
    namespace: shortner
    replicas: 1
    image: bhatvinay7/url-shorturl-converter:f95ebb3d5ab7f40b5d20812ee499ce2edcd3a375
    port: 80
    targetPort: 3011
    nodePort: 30037
    secretRef: url-converter-sealed-secret
    dockersecretRef: docker-sealed-secret
