services:
  - name: url-ws-server
    namespace: shortner
    replicas: 1
    image: bhatvinay7/url-ws-server:f95ebb3d5ab7f40b5d20812ee499ce2edcd3a375
    port: 80
    targetPort: 8080
    nodePort: 30140
    secretRef: ws-server-sealed-secret
    dockersecretRef: docker-sealed-secret
