services:
  - name: url-ws-server
    namespace: shortner
    replicas: 1
    image: bhatvinay7/url-ws-server:51ad780a6ce492def246f5e4517a9cf89e6be12d
    port: 80
    targetPort: 8080
    nodePort: 30140
    secretRef: ws-server-sealed-secret
    dockersecretRef: docker-sealed-secret
