services:
  - name: url-web
    namespace: shortner
    replicas: 1
    image: bhatvinay7/url-web:51ad780a6ce492def246f5e4517a9cf89e6be12d
    port: 80
    targetPort: 3000
    nodePort: 30139
    secretRef: url-web-sealed-secret
    dockersecretRef: docker-sealed-secret
