services:
  - name: url-web
    namespace: shortner
    replicas: 1
    image: bhatvinay7/url-web:f95ebb3d5ab7f40b5d20812ee499ce2edcd3a375
    port: 80
    targetPort: 3000
    nodePort: 30139
    secretRef: url-web-sealed-secret
    dockersecretRef: docker-sealed-secret
