---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: analytics-frontend-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    combined_env: AgDOJgQiq82SZZLdWmUq98UaqcNwRCZrSuRYsVPtOww9onZBwYAdcHBUqY1FO5VB3LVGa449Vp7Nwn0VwDc7ljpmB6YqiSC3eAgAZrrnmYx4ws1C2MGmVTSP09dfQlXt4j0oJajhlw5ahkznjPzAL9S5Lgw3/JQRB4TJj4d34lbLWRfWjAHK/cxgkam3rNF3f3nMbtZ3W13VEQ3KD6Bp8DKqQnXl82BrtcLkVCtymtY5hZv7S1bacPaKPSfw1WY+LdUNNKdfTve+AUawy5tCOb/S+D1rnto+mmaMBo3mawgRzvW4mZuRn2ligkjv/5l6GqmvljO8jDDdfWR1bWPo82IMIrzhvssG86d5+nRuLyXUPpjxK/F+f74PQFyuQAhgXdP4OQ3d/8WzfK3WHXG0ZP7HXn+kcW4EOAuQFb8FI5QUJkUK0MZkevjyHfusvgK6SGT4FHOqnEA/Gqq9Sm/yaHWS+6lrDichJSPWUvKAJTQ1pT2WXJaV1kZA3EV/GUN0ZJ77RoT9vY803v7kqCIHlxlLLBdBsEvpLiC5EE3oNUC9yMo15zMqP3dbqtmnLdxbWeCfVEIcF1r9hPpuJaQZrRMp7Ni6fxZO6eEeh3+WyoINWXKPcib21xWwpZSlZmZH6kZpl48/qgxlWR/GrhAK/AMQEDNuyYEhrb8CxZp/99B1j6IRSmNsbgkFuZFFynhShQUz1762dhJtESExY62HZe2UHGYTcZujkV6+tJr/temWOU+CL4pJ4GA4zcp2v7pUDn7aU2E2T1pM59iVXPfA+ni5bNV2CMkIHEGeS5A4WYbgpddEuyKlT5Gha/BxAmpt2CoMSqQhYhkfqntmVVYx
  template:
    metadata:
      name: analytics-frontend-sealed-secret
      namespace: shortner
