---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: analytics-frontend-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    combined_env: AgAgNxkB4DV4OLyEI1BI9dtgR3cLKL31uumxKU/6+33DGYbb6R0xpxAro19pW5tsVyqo9EvaROrNcjUy/O1Ls4xW0Tig5VRE+UoWFAeFza1B8eFhSd54ACh3fsXSGTz6nW2Xe4ghBWwUtBHOuQBbBdf0eQA2bIUAQkCX5HBs3l83hGdHcOQGfa/wQOYtNQksg/xQcpjWXbE2rFc5yh4Uxk8HpeINko//oj5ErqDhhgIuRL2zz6wsITvI3Dm52BdqowHmny5wiE7nXoWxsry2T5M6XCTmFpzgvAXZgIRGMp1U5+aHVFtqqzxiZ60VebCk9LdlOR2kpL/m+SRibwNOai/CbWWUlCha+OQDCYRbZYTdI744N2MAsqh80t7fbpU96FYiHraNv5IQbIOYNS85UfKmFdVwSq7zmqbt+ul9rvt/+tOpE0OlrV/71W6kkRdCjZS/83kl22L77pr6CeRUdrB0btyWX020knDVm8hrmYBTr9J/ucK+g7ua9IJM50T8Cb/bDSmbACLOnNu04bZBqCSI9WfXpXrSLBNgjYlpsqfvQzoewkQASpzF3JQupBCIWfTcitOvlIPRtnnpthIaehMXVWAQ82QqUM3Awa8rO7TZpif7By+fvZaixiQdR8v09+VRI+P58NGO2VZfAHbCt3KSBbcarATvJFkOGpAtTrzex1POT7ggU0YdXmcfi6rLbTNlX0MKkOV4BTLSfN981aT3tEsp/Dqw6WSIwYgqo277JahIuEKfdRMzc9ro4YFQrba5tfbX07a8k9lGH7Y/Uyg3+jsSDGbmnwKOzLhs+ZXLstzZh5TrcSkJ8I9uFMSAyv2ENNcq8mNSmt55PvZO
  template:
    metadata:
      name: analytics-frontend-sealed-secret
      namespace: shortner
