---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: analytics-frontend-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    combined_env: AgAqE95AZuKKsYgjJW71WQziRm5Sf496dY+gXCHhUzyqTamdtT/BHd69klONBuuMJh+oszGkONZzQR6ZbGwgyDoW2sIoj2U6kqZCcrqJVXChmJ3s5natlnzZIc//fSRa7c/gWFeCpnuLuJqnPLapqFaCf1YqDTbG5HzRdEDk1igN1oS1RmNy/I3gwUBLaSxVXaXdCm/thnEAi9cpCd46UsVv2Xahq2W6Yz2eBr6h9XgJ5GlNjpYedtJTqr9L8xeGrPw1sy3QZeUsxLzRWx88NQdFx+VYEqvT0ksR0IBGQUjP7DXUAkPQiOijLVSt7BsM8roVxspzDzm2Pxc9DNSbD08O568BogJ4zznoZjt9x3Xinzbsrz5HrXqjYR/4vo9fyfhAoPoiPhuXJEgbc4Dt5Sxl3/LtVyAapik3UOY6IWhieM0rZ8gUte1VcZOywuFIBGc8mtUAb1FW08XD4TLMlzsfe3cYuf/3kRYiSO5coIeMQwN/QnygHVdPHBdLVjtkyKsCtmJ4pHEd6uoFW8WjeQhbJHlQIs5ZrTBcm08yKlozLYFEQwNrlF1YGKDJ8lsgZ6VR6OqZsl+NTPcJ/ik8E+L4ehlOTHhhAbqag/QdiYvlFTj2BKO2AtSWWYEp/9WxVwL8xCS6Uu6Vd36zALNm0sSPNluOEhTpqrA2p0r8ii/ZTmJm922sabPtXU0Eim5/RiGEl1v9djccaJ5L4+BCFTKU96R/vW4r9NhmnaPbocyffRCNtxZeTmcr0yg4quT0ZyQVPHcoLVNtjmvywWO0UJq51jHiKGWRYWOoVlP4spgT7fEHliVCwbZxtItZBnYYShO9p9PGjDxVaZ2Q5c3K
  template:
    metadata:
      name: analytics-frontend-sealed-secret
      namespace: shortner
