---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: data-collector-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    combined_env: AgAxgOfVAoz+jIhVAtysJaPHrGxkiaDwmV7yXr7oX1fdFr8QyKgfOdZKe1YvsM8lMkEcHzKJCYCtY24eO2A1UKSV5nNjXjrm+mAW8zjwnRGKBHrBZqvpBLsQGfnW176q/zenq87WN0BsxS0xZ+H2qIn/ZphoEgHLOuQtVMLrBA6WgFlj6e7xJL/jDrbxRiSJgJDB1qlqUC3RxIFAdbOPj50JcNcu0+1P8ZE4kgy6l46nbnCWYRsVR2pniZcA85jVxsSvYWceSlk/SjGhN5usT4PsgAKVRrPjlMYoUru0LGSiuvSx9A6H/YvbteMr5ecXQ5ibCS+5e06zYZ1VuWX6mEc99Qcl7+4W1w0sCCDDVblQUqyx5g9NlWrw4/RcZAfNLlFOnOvB6/umnO/vgKXTSA22xdNgbDFlO6R2lBpI1rNXZ2e9ixOxvJ/DgoWPEVuF2Xhf0AbUNVzWb+sBRnFbbXnOMNIevRUsW2z/0h14e/OFxID8DFzIR2gkQhQ/h8Q/dE3T525m0xCgZ1qLNewrlDitjjwoMkvsidB+bkAU1QA0NlstP3V0EOEu4TjZbrd+Ek8JYNrHoOIEJAiySwj/NPMmzbm5HZ67NBHsxypnMtzC0dn3ibYu+YCRX0lgg6f+cKGNaz+cSW5TDRITv/sLDVr4ZuOsqxcz+Cs5fuX7yHVAmyKGdj6cUixsmIHLKdAJpd7lkzZlg3kw7a+c/8vtn6H28Kx2sBQI5p5FI43tucvjf3a3zdMjCnY9aRw8I9q9qOXlb1FSH5qO0yrEfu9TD4E3TSIWBabr+MkgPIBpPNRNFSFBjcYXyspSRfJ7wkx8CIsy4DG06QnksjD8KDKeK113yi6f/7k31o02XQVVGv0dwODiKE1K9xjmieAUNFkokA4UpznBS/JYMniT
  template:
    metadata:
      name: data-collector-sealed-secret
      namespace: shortner
