---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: data-collector-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    combined_env: AgAIkPX3XL2l+9xwsPAVFfMlYJBRPpFl5/R+Htyf32E5QqWM3u+pvJkgELLpWWc5yL+AO2bnCytcryjBHsKj5Wpz3I1qOUiihh7jZKdLJM2iXeQJn/GiE0E1RsYEU6XgFRQ//W5QFmSXyAjbtj9ZJD/mNmxdo5/rNExuPax5Ym4LnB0RKOwRM7hxpIEcD7Q+Mg3XTHs14Wchshgip1yZRoOg46p7NK9m8mkRcC0GlxhWIxdhMavCg3qLyGHXtOPS7MzPCIGwJPmZtBtBFf0L8kJd8TVwYlF9+hwPn5vMJXDaPnjhK5Qip8YOgsLwvXPTK4tXDtdaIt/k4ziMWcAJiRwwqQOptDvzoTmp+neDG/qo5LX18YMbFmGTynE7se0uVnpXgHKpJ0ta5qZ9fHuCar5a0TZURU/204qp5u39vrnfz88SjvkKwAiVu2rhyZ9VbVyKMbhw2TW30EcYyrLgTuNOck1ybQ6YO4bc29O6tLowlit8uQaPtp5r4bI31qMONFHquyrt/dWmiz6N2DBOe9FtqWEoLJtcr6nLPXkxsW88QIoJRKpHPSJ8osZ9O4pPg0NSiJES9egM/RWCdkbhISaPdZ0RPvQ93xtOgWIusl4O62bzjVUYx4AZ1+MAF+oaypF7F556Ht4LEbGglbL8PjXrNKdr2oaghj1XUIfstco+X0Vrn+fJbK53B4I2PDwZa6LpS0vDliC/cWuXFc808FoJqg1x2gKrJMWEuQV6CDGhVHi3LZkxYe19m7hG2j9OWn4yJKa5RdW0cODS/f0ZC4RdusC5wE1E0ws9tqDG3p2UPzWgwuF2C2dTKbLvBOjXrQVJkGsqw7drfI9gtTZ8de0Oyx2Cx9a0tflEawJ/PLe3tET+xSkouyO9WVpb1hWVbnEMez1FW7Oz6cW5
  template:
    metadata:
      name: data-collector-sealed-secret
      namespace: shortner
