---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: data-collector-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    combined_env: AgAOOvUlBMJsErVG3kHtNExi1osrRxVk9m6nJhJrCGgPg3hCCAIK8yhmxRjCkJSspGsafRjL02RponeJSqt9qkv6E8EwBWxJWa3SSqu65du4j3wysLygp510iFhoUDCrh9Fyd5HFdl+XGzXy/rVSd1yzwwgl+kporbKGsT+q5fkQFx3m+2pH2y4Sbbh0YGdMuniQcTNEaddFd2M1s5K81UGdpGYaBBliwWxIVhzNvxSNm4oWtv10w1zpCPd1gCr82gXfW/YpBvKV9xUgdr3UpnnT7AwLCjeys15QyptOTePlrRuJOkXjtxT1XXaZJ34QFbDoKIXSG8KMajU6CssCA55zuobhkfgGtc1HxThwEo6bW+6xhKU9/vexVdog+UOQ9MCHzFxdJKVfkj5UtzN+i1Kl066JEioSkRxuimsaGn+uzOUTEjdqBqJ+fwLzK6QA7PQX03NOZPygdYlK7174l7wphrFmN8irLpCBp10zqNU4rBBF+IE2nfSU/Niv11IJvcOR549rzxp11FfrXTPyZ+LIsgu/gfuuPxwtbtikLRSPpZr0+bh8jhUEH7ptgzAhDfsei05c3M+VKMfEFRdoyIvViLC8UF48wuWqZ+1pi5aPisS4mmdq8kop7nNHq+JXNeLw4eMuyIVtzQT4Ff43Zv0l+LG+qHR1DHV7sWe4nLklV3So43id+t/rkgxaY6YdmHxg7dzl8tbGeG7fMY6WGnSI/LKpXDUQSl31WSqGQwOYkH4byr6b0PBiIQTGuSykE8DlLMWY2JayTVwDds95P+AwQvMFkR3yKUgKRMBteJjuz/fUKqXCnIA6D5/NkgUvGeodaHIfXpq6g+VCnFKS2EbWzq2hDdb1ir7z6UnVWS+OukGxHnXwQv+NAlsZdrkqL3rkafMGcXxGY77y
  template:
    metadata:
      name: data-collector-sealed-secret
      namespace: shortner
