---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    .dockerconfigjson: AgAi/8fEhCngGZOjaCWNI5+qfB8srsWPBEs0bW8skrBAXkRTXnNN2fDLTn/qDnQydW1P/TtN90Z1lkyd5v0zY5im5ZKpZt2xgO3TTKFg3JfUR1zE/evQwBrLU/mEs5DeTJF9BH8ii4gl8AU6PNTOYmrXVqucpeCNfaeDJUb572RyAHDwF3r7LQ1mejSIESeKlBzmDbT0dO94DwoKijTs/Lo+Hlo+HgEVStvwTsbwyR8OdNOHpocdM/j2SxyrD7lE7C6/y6wPDkz2Ilxw2/OxGio4DpCYkfuYuCzvPmxYOOibWKTGq5ryUVqALOH/YZ7M2pW8jid9HfIOdNYqaOxsNBqQMVrY/TRUS3glF5LLBf384pFXQKsltBpEs/awQ/JUO5W7/WpymqgSAeCfefgTsW8xz3CUoTiYQJbGUYlKVLmlECIjjJZ8jxRsNjO8/5mrNaXbzVFFD6NRhIpgjxkqXSiRPFJnOxk+GI+/CNo3l81kjDKjy/PGD7CDKjwLGjDzVLn6q6RhK8J2XvFL5PE49uxsEtX6db9dXlk0boWi1BH901sKR1NVnvkRUdxpooqFHICKpzf509xwk2VQowBawaXRWQIcxQ3vBzlpBYfnZCiNs7ZAcIEUt/pqMhena2VGvd/kmCgk3xRSCUERHp4ZBxM2nf4WyOfZFFm/P5cdcCSnnwqLjMAb77xVjKos2oZ7+s1mVXO7izg5Wgs3ddnOFCY2qYMPsPekTPlEGM+P8Hu6xieL+LdRTJpAYdLbWqadUP+WjcVDsus64YFSh2OWnJZMkAOxf4Kpcr5g5327Q6zv48v/gkN/aLbOA5dUt+Tkf7g2l7UJIfLjUGjyTvhNhnutd6LHsHHyGV3GYWGg9EdvmYnpAnwpSoRjJMcZWiHmNvCeJuoKH5djats02/iTPM86IO+FFYm066UBHmX0Smc=
  template:
    metadata:
      name: docker-sealed-secret
      namespace: shortner
    type: kubernetes.io/dockerconfigjson
