---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    .dockerconfigjson: AgBNyqaWU21/TmqVe+YJnV10CRAUP/vZrRd9Jjq67DEtPBbvCrWsA7NU7uXyIon2DUUKRCOp+QfKAVrCfmIH5baQmwKsex7IMjPnOVgq/RAswUBEPYlojT+htfQXGZ+C9INBrB3NXdyU5hNQ0qF4df5gBs9QMMR97HKg0/Uw+VPrwwZFF41HiHwfbdHwKtSpOUhJ7R1uCDxuem75DRtD75gt5UmXlC+zeIao99x++HLu/UiujYPRuYzrQBqCtGexmhiTvkq+JJp1+W1AUGsI9flYfFY/BBZ/P5krXkyZHdR5pvnJlMcYbBOEiPTphZYe3Bc4xFLw6ICukjZQAXCL1H2G3RFFVKDukY69OwbmcJKd6O4pzYGmLZCfNZSTteGOewxbT1FTMqgbPEfQzb2rv/i4uPyGDuWp+nqBaWBBYlAGdAMFEoVdj+wTfDUHvXi0Qr1E7cRZ19lRXRKQHHNrLJ43V+u63DZbBMrgpIwjVsRtFm7M0ti3rJ2bB01P6sdhim6FQA1KlFBpPfrrWkBYr8G1sae/vcUdVvSqtFFrtUqO0y94DBgOq8T2Cif0oX1pCtj5OUn3roDACdAT3udObAnVsH9JvmUDeG79SmRFNWWScxe4beAWqy0iuB7flw6RJZRBElOU5DzcRJgLmESg3JH9WV58X2jIP33ZSMEffpTIVvdYEAQY+9kpCLOG+7TljuIse5/ztErZPWtvkH3kab1yai99HabT9bpMMsgEcB/mfGt2N5H63Bp8sUQE6qAlOzMfrDynzOCzzUpXFWr05yT3SDlrv9bvSmoXxQf1YWfNNcNQk0oFxy0qAblD+hGl3RFxEpQE7dsViLPgyMOVKvjEZB2EKQwkJ+i+MPxndBQDHThCwopD2lRlIhmfaKEPPEKasa/tdrWrOPKb0elXvpa0szIkXA0iphr/hVyVVxQ=
  template:
    metadata:
      name: docker-sealed-secret
      namespace: shortner
    type: kubernetes.io/dockerconfigjson
