---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    .dockerconfigjson: AgAUxVGYxaEj4S/3yHAZKnZyk98lse+YLFyHF39XLobjkdjBfbRoI2Nfl3f5vtIfxWLY4wtc3aCI6iuXGFTv4kW9ZVnsoAzPAG0XAioJ4ksSCXsZVyUAolIvXVDj15Pcwa1D23VvEEjDk6QewCGSWn2RY8Dd6InYSt///lF0JkJTQhpV4McagX6Fd2FsKqs6Ij95GSm+qEh8JgC0yxGdXH0zC2f3CDrX/lwkvQE26kqRWyd47T3Zqb6R9H8KTMpHVsOTJ8WVspXVKMVjK7EwB809cNzmll8EdUtv6HZSa6zGOGkr+a6Mn5DIjqIq0b7YXKVsos+piKreMDd+91TQGEGIGTJighoL3pTvOHnS/1smJ4tCelVB9P2JjzZwE5XtDBpmJtgKGXFW5y+3DCrXcbOkCNNLK7jiDWl6jRVIqKH7bFF+r6y1D8bobdcXTmkaJ0wf6Sdxvp7wFGIfMq6e4IhKjxF9xgjfIouZRHth51Py6x58D6CVwPIoAJDvRjEiqM5XCL+l5NsClribUvVb6+jC/JpinyZAH9OcDpPLdoWLw0AkHBBAs0FC9AAazKCQW3W21EoXW3h8PwlbO7yU/pDPw/vcBOMpLW49k9abXxTuRE3vQvEAFzjL8o3muahpbAEVihVIni2saEsGAwsehtCcxZZoh6PmzOkI+dqKtHKcpNKfzfJyOBj7ZMuY2jjyf/f2XPN7jo+muDcbIvZ/aOgyTp1MjQgZuctdn0KqfzgK50QGVFgjMxOnMfdoHvxwr2pq5+2/Lykyn3qErwU0+ts1gZ5f8TYlyumQ2I//XYfIeqom8zFYUF6q1jHMqvGQB33RHg0MueylkHvAKAlF6hREsAEGCLM2b+EWQ66hMk6enIqWTMFZDHuKjkA4pLwJR+R9B5RqjrF3LJhODMrscrKWzxZoSNLXUpZPZzY4yZU=
  template:
    metadata:
      name: docker-sealed-secret
      namespace: shortner
    type: kubernetes.io/dockerconfigjson
