---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    combined_env: AgBwcYblehTe8HJWBrVNzEJxgtW5PIneVCKjlint8f1FvIf7jaZtMyS5qidcR0baL9i6ry0zjvBEwxzsxqnA/MHuCyzsdICHl68VSuBD8+h0ivyKv4QqotH6DuMantDroRmA1Opub5AYuV4zU7/ftXw1U5Xr00mWoHGgVwvek/hqOsz+l5hwLQs45bF52Ie7woiocb5BTTuJQKxA6rcHvy4auiCpWYvhbPzr61ucypDh0SLlk/MdbMzNAwQLdhvrR8SLw69iFTruKb6Dc1t6h03i2Cm1eGSwoEtmg6G55kb/u1f4GC5eriW6HLzFNKJWrO+7vh01L0lvhgsSWyGgVvleWRQORZIjQ1zvTtsX7geqtJHsPi2OSAcskmnqukHxHBiCstuh8bscoFQ3fldOhLMklHrq61dEGTj6e8Km8HjO1b/TsrWthg0e9eCp/ckZ2DQ5N90XB3Do4y/rrB0qZiNuvts8keg1Bse4zTSaTf+fpFl8vf3AUNalIoy2MxuTH3RQx64vn1eliJPeMI8/bEGhiED4jktTs5cU/rvb+I96f1BXeG4T6gRugnPw/BaRR3RB/dQ5Uga0khb1/S9OlWClTRxlMoDViXBW8kdNaIIBYBMCW8N+ktCeQiXpAe+TZa26VUg2BSMWI8nBhudNDZDZSa5eSbJGlZKTm+JfUlkcONY87JEYkMMx4VAzm9B/KgogsRmyh4FRAqDRGmqfGrXhENKzlTArG61X3Cx5KDDWT+bCkjEoyheButu6B0J1z/WhhCiDIDiB54dUNHBUvg9yPQGnPRSIskI5E64WQPDBPWWk2wMGJOA7h+YSWjz2Qkfxqsq8eOggVwP4CjJEiOitEsF7AvnChmZzn1bcqu7zwVD1tvAnvC+R+FwUA5Zai310c0nxeE+TDA==
  template:
    metadata:
      name: frontend-sealed-secret
      namespace: shortner
