---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    combined_env: AgD0eWCe9yWXRVJChmfF2luFXASohAk+jrU0fguUdjX82WcUG+/9vWru+3MQi1WJzNzXA5RPfMSfcdLGwUmU1EiBpZH6Li8SV8FWo9PFMsyxyRaVbtCy0Q7RA8MhPik9O1vqcfhobHhMuN08JkFUHvTabKdNTEn3+o5ETjeVCSDhMZwmTpe9+o14t6KSI2KA5OUiZIhBQgOz4ZxmAtPqmZ7fGbDUYwobB5SfEPk827xT7eZmgh+CYcn4SRz89XjRjQrvVogPq17kdkZg0RFyTXS/4kn/WQc0iOxDQr5hclKv8pEzPe/w9LTe1l2dyBLx1ubwaBHsVJnPj9RRjAl9JM+FENKHJ74m1CWDgg4gjh3Knd/MT63gRVDVlHkfeP+IrmsFVtUIImZ5gO+Rtuw/nsrbYm/yF5qOc9ysJVsH9/wfjEGGEw6KiTQ/DeMAQrMowENL0c0JEL2io6yRrpP+I0zaLsJTWsXaQPmqcL/397oFNwiHiLKDx9uBVxiaY0NIdHWwlhh6D6L5kgWzXfBXXV1RbsorR/eXjyIhhAAcJ/glKl8bI3B8DtOO3qvIJRfvt4so0m9zNxBGvNsJKvjswUXHduhPoSivOECqYYp+DP1D1BfZ+R6RmGcEpjFOsofJ0j6WOK2A3JfbJD7/ppdXDd606MYz0nMMakToCTUS3F4opoHvA8lV35jM2GB6RlsXkN+8CdmEQ1xKgdtM0b8sxJIJyaT0zxOxwzbmF8gIChXWap3sG3Ypdc/Zwh2mSBugg/djW8Gx+GPNxTsmOuSENVa4UaYvV9IEJcwhlGx9Rnjjk+RYpslE2rcBFlGj1X1TRdxo3q9npQKYTQwPisrcgAStWW7A6gwHKsfYye6Z4BFIMC6tJjyi7qsZsj7JySvHe7ZGXH4wZgwkNQ==
  template:
    metadata:
      name: frontend-sealed-secret
      namespace: shortner
