---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    combined_env: AgBW9+iF5yX/qFpENRB/rNvYw55777HHvqYsp/YyephHLpBlTu9YvPGTaCaL9Db26D+41MCCAcUFmiGjGtDwSPe7YAwKyA8M9XgjuJ0GGCH2x9tcFaDYRvZqX7A0Cr7Gt0YVqpY8Z3biHUVDb4XAEXMgeqWaVOrr7WbtAN1dHgmUMUZ8hNKwyoRXCbO6RPTUvcGd8761t9XvWRhZJ7WC/48bxmhP1uhpDBTwC48O21V+arJXYMlEn+Rc/7t8MlPDLNnMVA2cEB6EK5XgRAt6zVxId5L3w15bJJ9ALWMUJ6U+9AGhaos0Ffx4/thzI+kudk85cliC/tKVDTH37GhDciFLCi6Y6D1yDQZNVLROdJp+2fvXLBSg0GnCnCqb0rL8yugUvZONkB5gc2zgG0Zt86j6QGuk1ctW3Naevol3TPmU4t3NuXiwCQdhWqYJiMEpI4QXpGbbt1wdeUGqLaSDgYYHhng18zs3m8mpzvp2qpKnJ5wqi8uBKmweP7vR61AHJekGlLAwY+YwjqOdD4J7Yd+mFWF0CUdfW4ULgW8cwG3d+FIEvQ1xdv+SYIWcMMe9TOA+VLqqSKqx573tZi5w831hg3QM94Zcb3EyTPc8z9yi9+2s/cNgGIdeE5VC0BOyWEQ1xnN/W/MSjiVofKc+euSifzm38uQos7JlguUWrc+mH67BF8ZjJdN9mih8sPydgaRjquJw9UCPABnGr2jwMukTcidzzg1/PZyox0hlZHG+VJMvAa9ZC2a0WclHuiozz2uk+lIZXKHwkaGgrAmZKJXTtFSMwIjVCzP38BoPru+KksJK8XDQnLcLL8O6OCcpWWE4zjMLXSNo2WGCW0AzD7vA5TJKcswVJ3f69ED6rR2KxgiRw6Acr2H21fX5K3ZgZI4S5OUGumVNIg==
  template:
    metadata:
      name: frontend-sealed-secret
      namespace: shortner
