---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: http-server-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    combined_env: AgDmSi32nzrnMhB8RQGXhPfkZNJfpinpuw+ovK3DXUO/S59s65pg+r5S36N8sxd9eZNsvycc0ckp4+z4P3BO+aRmYCqDoTKi+DLGfYTsp0aA2VuPfr65hYGbHqg6osmA3uztcx2tKvpO+9a4NRYx4YE7xf4OAWpwrr9+X2TFGPnnUIcr6N4Je75Noc03knDKulDNN32RQkA5asTBwcDxrjahQY+YUaxIfu3duMKckN2m/oDISiX5oC3pdTD6lWJmB30nZ142OFm6Xww3EMwELogdlRWs/iSi/CtBRV9CI5HVfVttBhBAVJmA6eS7jfPc0jKL+f0/AiFjxbXyTurOl4uTZVOQZtSXnbwW8PlvOppxcS1CGXisSKiKUm2X+dXfAQAwlhvBBFe5wJTItTpiey8+qY0q0Jh/GJaTkJvdfhcERu0N5/yTfgm2z5JDhqQFqAvebvGcFvk19qs8TNEnh2lwu0d6BVlP7rhRf3J2zXIMB4TGfY9OPKh1+eZl1sB4vZU+9LaPshTE1mykW72xyx+onz3YfwtZfv3g7blgo7R+RB4u5wX3rdsHhayBCGgYsgRv5+ywDjyHCIKaRTQ1ETLciMJTzXWHn/3SxG0dMFmibQM0SMLF6bfzdNyCUFBQs2UHtuQx++hpfBtT9gHl92bipEUmgbzFnAppdOAzPaFtW84QrVwfDV9UpiDg5MB8zA8lMCXuIIeJuNwgjWt6EpncNCg8F5JEJntAx4hZHs08cvVTnDpuLe26HA/iOlDW3CkElYl7XEfk7G8Bp8Nf9C5I07fhYQ1oH8NqX4PHiVgF5g9dQPJUB1FMyLmfod0uEZuLqB6B7ijtRpak6L29uCU9A0OgI6m6CFCk0MJsvC2ClFjAyrNrspX0CVXBg083/XfBHKxw5MASTb61fFIOVyDpw5Dr3B0mg/Q3a7ztk7c1Ls8Si+PMJjOGcXXjfTDuqlrnlNaG5rgtgUSFLdOUihUHeHamAoQUgGubO/Oir1Z8u0ehUczZGDe7dip6XUPLwAwxKSBiob2bVV1VkZ7kjc3fCnMq6hGWOqWxyzWxdrtJ0gnd03JpCzAJMhYuHlngwGJ84RtAF30DXn56LJlWLbcUB+tpleEn1KjkwgHnFuiXLMyHzufAGAQ6gpp8Q+B6wIGark8IvD8zBFUbjzpdatzbkXHjd+x3dHvrBbVmEcvOxb5NwzZEoDQ4c1c5Ksp9zzEAggl9miplDhX47tUQyr/jEFds+/PCm9hoIFHhFNd2QpLPHbAv7anCavnb/BDPM/LerCFT5p7NB9J6JGkbm4OfGF1TV18ymEpMwpWyHaA+dDHLXnNpoIWJcxYmBC/bGq7Rxj8hm+WxNskqbNF9WlkfbepG6zo=
  template:
    metadata:
      name: http-server-sealed-secret
      namespace: shortner
