---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: http-server-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    combined_env: AgCvUpElwD9vrPKjsIfXckAWCwfQOPjIvFBg0fD55h9FuLQ0pcyWbs1gQJ2m5b6kWpoXwfhsyf55vf7oloMkxvc7WZy68FJW28UHPdVhlr6R7nmaso2m9IPGCGMpP7qZsLXJux/gCI4upamIPPc+npWRu7xvi1INLWUZqCntffZdHl36NO1bFU8xzF9O2BUmZycw/ayq2uxlInvO44VtDwoidjDzKb0X+1TU2pZRf6mN+AOHEgfkOPrWMiCq2VhiBkrBOserpemqzj3n9bmFlkCOk/biFivxN4zMSqJ1Ekf733LGEGZmb+XqPyxCPRINsMKvn6AVYVfL0BS3yJm/ajZFsYEiaOOOkmGrBJro016U01qPxjDifl88yHdWm8XMvvqO21WdwJRtsTjxJ5zmqkEbWAAJZFLCH7iID1QY5miOmo85gewJSEYApwihH8zlUk0mvI3U0QJYLIu+w/m81ChWj5XwOGZKKuh36JYNA5KLzSzU3WS2bhH2JY73DxfMV3w/dOtUDRroH/ubzns6ljo1oLOARkMrg6KvD23aEl+71UtOGqAESm7Ia4DYMgZgqJmGEgL0CAhOa+ytD8k6dDMc43Dfr7iaSP+TSBlmDXmaPAAURxQUrFwQWScNuW3KUI9TTG0iizXCS3yfl2pM2HwIo+Aiot7vgEQE1tt0bS0kHgdylNjiN3lrJB68dkkwTO9LqZHYuvkC0uqFzW/ccYIun8f6t/XNVlPctvvQZtbLHDKW+els+lElkpfnfRihLQdL5fp+yYeOaNr8dBS7dAknQze5HyxguKphyJFIUMD7OiUJfWU2PQOaKj51hkqjqu7Yj8jNF/6AVc4a44hjXnx++cK3D9SwmsstMitqddFD+3Bd2XIROaTZ7HOHhbekvALFdg9URrF+Xhi3+Gb71/gbyAz1kLWdod0DH2o6E9Yg5Xf6mpBH7cO7FpV/GMxByx+BCTrt/lOdDxPqSiNoFfgzFro+UcWuEyGHZFaj3cVl17Fne0ll5lmB6Wu6/NhBwZjQEtFL37fqOdKdAvpkjK1fZKRxuWwCmhRysa0SlWwKipPn+kbk8k5tNSsHekDoJ4mz5I04PS8lWpKIDOl424wtygce/K8ow7BO6yH7nOFfpT3/U5kBLCyU2PVt4EwlfJaGipRP1lgESJthhrrBxzb5onzM7fT37IDF+KLmyyRkETYXcoOayF+z5SUXKHLEOC1V9VRZVGLHuHRaLxWlM0H1hzKdaN4HHRO+EhYsPURUnw4mkqosB9m1T/vtxg8kgo73cDHk3GwnkIrNWn/mR+adbEjwzISUIqAcO1xvnmDMCt7ROO9j9Tj1BMaH6orwlWCYAQ1bV1I/nshbesRVYg1kgyHI26g=
  template:
    metadata:
      name: http-server-sealed-secret
      namespace: shortner
