---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: http-server-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    combined_env: AgBxh3wWIJNO5ZND7ftqQAa9pghuqZlzmMgaPinkmlbFVmtXb8g194dsJ7jfCSA9V+MBFT5HD4bkxjRtfwoZZAY46O0pXLLnNJoFASSoeNFLM3OXct+/vlEiCr8AteD0A7o/MQ+i5bgd8bCTelZzecBrVXduDHX9Gek056BGIBV/adnNPyClxkBr+LEimf7ynBYW9dTTpHjINW8AQ49RFoDshonXLVyCnUP5uQQ2PTRiJ1S+pKveCm8snR6NJfPxjWmm4t/Z4fu9dMFXnDZ4sa0hyMT3E9Fri5aJMTH5QZQw2iVRZpc5DWnDuZkh4DmiSgjyIJZsGZHpqugWOQpVQImBAQMfxLwgWDkG0QZbh757JF+VjXdnPrOgaeIy+nLxn0A6/yxu40J9nwHUiQRhIWgPzZlj19E+LdaekcDVJZlB7rzKXDxTTVmiftBTOkCNw95Smb/0evWZBXNkIQ+B+6RKSe+k0wEu5er/DsPSXTzDASq3U7M5aetOQ13u8cymqaslLla6M3XbEGeL9GvTejB3RQz+Znun6CC6OLEpiS7dyYqQSmvNxnp/61A92EpUxu4k7ub6gUHs3BBe3vywzVTJkaU/LmXODG+9CRe/5kfayYPEfbwjJhPAU01JPufeYHX7DeV/h/pJf3amGNK8w+P5/1oNSa7wvFPG9Hl0smrVaIOo97tLwsZB9znFxTFCC83v9rA/Q6DxaLooVQGLethnCrJBiR4j0PduwR68J6CuJ5BZ1RWWanFP9eF09lt3U3lPxW8fvxUeA0uMSz0o0DJ16aG8S9IGYHOfR9axhzePwpJZxtGA/z31sY6jmnIJJOzDes/K0q0ORuXqEYr65M93otXC/KXQ6gXTPYxOsrYGHdrgusQLmRsII0Jt2DYoTIJfVGp1JKp71A7k9fv9LQR5f+ZmVYXgZ1EKVCDc5duiyPLCGcCreo5Fqicjvke66uw2L1IvGhQh6OCf8SLekRZnOt0x9RfCA8EuLIpYmg2gRvR4JpauHT1bGuCnRDTmSp/FCDqs21Wn7SJ1MSUULbhcZ2OyRTo3vPZoWZAnbb5c7R1qZxldqfbKcV5ESbBriCvcjnl7C8XIDLvsMcE+BNRoBL4uxTXxl+PH9U/j9laE1BxUtqp8CPRSuOIkAr+o8eNLn/kJ7NkuKtXdYVgPvhC+DZbL3D9+ojM/8S8OLizDtqYkxYMeYgry+JuCJNm8w8d+7wZrNpvfnZjsEpRa3wqqjYtr6Y7pq85wjm8bvg3UgU4zhZDdnBy/hjVqcrQhllOWqb27W7bliGrgADke2O6ei4v6OsVOanDvKYtQzfY4Vl1YVaEcA4v7W8nO4lvz8/K4nxEvF/lSplz6X0m1+C2dkgXeyS0=
  template:
    metadata:
      name: http-server-sealed-secret
      namespace: shortner
