apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - analytics-frontend-sealed-secret.yaml
  - data-collector-sealed-secret.yaml
  - docker-sealed-secret.yaml
  - frontend-sealed-secret.yaml
  - http-server-sealed-secret.yaml
  - nats-auth-sealed.yaml
  - rabbitmq-auth-sealed.yaml
  - shorturl-converter-sealed-secret.yaml
  - ws-sealed-secret.yaml
