---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sealed-nats-auth
  namespace: shortner
spec:
  encryptedData:
    nats-auth.conf: AgAr7pJzXczibx7ErwaMivPmw9WRpFDLMWcrN8zVu2vovbrtPDdt+N5KydK2MHZO4I2Nt8WqdxKaFFL2vn4IAq29efAWNspUP3SDueyNZU7eAjTCIBzE664Rd1TXSrvmPQ5wKvsGsj4n6HEA3TUvKBcuwzm+C+xzvZGbb9ArMY8UpHefvEM2cyv9MOxi5zo2Q/1Wnfd5K9nRg02uPioW1hwZhGgwXZvR5X5P/TlWmfaRRlVBhW+d6zJUPcSug/22iTQXtft3QTMf12nvpdKj0gcMu8CpzoTAiwIhSFEYuTVDXO0WKJdrP2yFaJrUBQFQhcEYr8E1u8ZMHGQkzkv3de3xmjvAtJpDIDdYS98QuWDJmMtVNjK0NOsUd2iSXcRCt3UnBi6wqgN7JgKkLkJSwi4JhhAOyYcW9OPTrKPZ4/zcJc9GSctdicq7frLFWy2zIArNmcVc3oh/p0xRBZzdaBCa9WwpBQ9vAnnPesvI0GjLbhjonwn1xblccw6jQEYWlxZRVj3mHGJiAGG2gG1Nn4mblcmG386ZFirlSf6kH9sly0bMQiDqFJc56I/IJ5BvfO+qHsMIsiVhusMyBLelNW6XBI0qyQpNBrINXEPlrQhl7muXQG2/2cKXCDYDrA3jAW+MJUy0G4u6n3tKFGvc04wA+KvrcLxIYDhuo6BCUaiR+0Z1we+yfqZibIbdzj94hHLPgkR8OWaUWpY80RJ5R4gOAPVwivRR+B6BYhIHw0hvp1iEMvz8JzCSns5hCrBx2uXir0FBp8r7eBYlRV2XG/3a2KS78CqQOlkMBKjgt1Glvpx8Et1Q
  template:
    metadata:
      name: sealed-nats-auth
      namespace: shortner
