---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sealed-nats-auth
  namespace: shortner
spec:
  encryptedData:
    nats-auth.conf: AgCWxwsOs1Rq6t7peWQ4H38filUgAMSUpvO8+Cttrg1YGMirJWeqCTfIxtmHFgNZtwCzk9GMh8LruHdtIpSug7Dxf9esBOHPz47r2Gs3S7D5O928D2ZBH7NryYZL20DFTg0QhcMstmiW6uAIX5HzVQnT2WdxRTO1giNDPpEv3w3OWOF8Yn1oY0LN3oqGniETbvrQVCA885qm4NaESFrSzgYWbSU72sMXyuBpjpQ2e784WyElKmOByyks9JNKA5IxzmajL62MnoQ5tSvBDsEpDk40Y9NFD3KyoM9B8tHfLV8UJq7GuUE3s09LJfjvg0BJPqopL4Q1b9riWL0BsGlL1B4pqTHtE+qaNwHnUdrRewlzwwG9SQ830RnMY6RuEcr4jndUiUurF6ikWyMbCRofV4CT2mCu9S9DrfX9Nm6TYMO8drVu3cM3iMTJ+AaNaiwCBfH9HQJCDabZpm4QFp5ZHK13WAwjQ/8/Y2TNtM7W8Jqyt8ADQQcShTVRq3xPiBztOM/Hxh/3mpCBSI3+mj2kafsPev6yfVoAXZqt4vob818+pTOzSFGSftMfgYDntKzJt8/omfM/wmhB93qJFcxW/rVa/k/r6snAGBHFzRTPt98qrAbwvV1+NxdaSL9IHwBKrXB1qyO6hBGnqnOSAc2Fhs6u5ZVQ1STpe8zhfUMmxk8FcesOa7Q5238PeAOqXSFE4+WkufUjxUjfS8pphSQbxABuhpHX8SQ9QOybSEFSHMimH9giNy0G2vrsTrmZRq1tIU+uEnNmTAw4fNSfe+ZMzJquMUeq5WvQUg64sfyP8uN6RjItroY6
  template:
    metadata:
      name: sealed-nats-auth
      namespace: shortner
