---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sealed-nats-auth
  namespace: shortner
spec:
  encryptedData:
    nats-auth.conf: AgA72viQ3XjYj9n8mKN/sA0rWHvOs5iA11Ba8Ieu8HyBV37Sh6RzDjsQPlgWq194uotbFY3p8bBHyA7i0gtgqIpkaHjiofoY482YgXS1kmgni/ltdUzRrbRgrMltGwf0VUSlV5kppZHLiPPwu13rxf8JFxHplIeot6aCvE896/W1CTCXAPc1aRB/32lE2DZ+IkDEoEFXnq/46GYPH+30Zrt9UhPg6NZngaLtLzlF5uqWoIpJ13KbN1FCm2T6a2hET6aJHK4TErZUmSoLIYK/pjqFcFNmTtxnfqbgoEM8/OZf9djdVC/YP/gBe1ruUZM/aNkoSvH8ySe2fC31HSqRz6kDEZ05h5PtXORCPuGkb7uw6Ptbu6oox+UKYYaU56oclcOSJF0hHEECmZZt1QVCliEOcBgCBM+VfxHUfffY3UyIK5qy0DI/2wcDMyfoYGIEL7FponHdgqR2xqB0Hq/qEVByZgwJutl/idSJFx1nA1LI/sJU8c1GjFRgmYwEqnhNo950qOPZ5J9TDU2g4O06qPviYXqcihUx8aU5BpqlhyexYvaiyorej4TXQ9Zqp8M/cECEQ1oNyf6IXORd7S809UWzPN1Dunq2hPVBNqLJFU04n2PQwniDFdnGuAWC17MFfjS4jE89CAlPSWYxexcrbk2NwLoOcSjwW8A68ScmdiVjjZGf+3X8e41tUJJzgcT2WnR1PCvN5RzKe5bUeG0xRJC5KkU6AI7vBS6qWLUEZE+H8CZIFPo2ybtYgEsIVEcXTjWgtcDO4NANcrwHmGTrDH9P4BhQdFv2DGRtOp7AJXx0yVVw3f6D
  template:
    metadata:
      name: sealed-nats-auth
      namespace: nats
