---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sealed-rabbitmq-auth
  namespace: shortner
spec:
  encryptedData:
    password: AgCdQIXrKOZhtkn4CR44fsLXE/aBa479eMUqSubl3zxc7+iTeRtDuc0plyTwirg7SbPlLdwqAY1uzpbNSHlr5SA8MjL938D1dbVZB8q3LIgfmqUsgkRp9jrgfBxjBf+EJxxYG1Z3Iv7GxMuSmgof8P8++Ts5FBprZjMEGTvjsrMrPmwQQ34x78foder6e/y2CJPOhfwnptPMuJPFoPGDiKZxxtb/ylJdvT5BJ9cLnlH7sFuwTP4QuJ7dzPicwZUOh/Pq4+pb3drDqkUKRnX2UZen1fHqI6FrWEy0yolZqoRJcTvl0osD5cFj0uv5XVng6KUbk+L3WJPVMT4fxvBtuleW73LYyslmMJqQa5gOOg9OyLP05/ksnqE3aMxhJMbpbea9VQo29pSqkF7drfR/DFo+wgcCbhddXVG0vVxnD5zO3ykJi0dqzAFGrTR2EV3uvILaf17jB3ijtDO0M0iQtDhIvPmpP3qa8I2YI9c8q63+VbkgzdQXLjOxOGUxFkbSDKl+XEE4Y1h1Pm/h30qeoagAvA6s4E6G6N+QJUoXk6EJyjYtBAqTNNHTGrC8QICQAISMXubaWgcEz7uuFeN2cKKekoDnDMqfSAntHfGU/lzmeWUfyknCM59+5HkvRgaDS/rj9quzvxbO+WPvql/+dmHoLhttbjmYCLp/+CVbu0Wegl2eIAyFJDWgJN9CqkTxiDe2Lc+mYD3uGJOUeA==
    username: AgAxuB7/Hvg3mWoVG6AVXo8wCefD+LQ0XJdfcdTbdpQb7gmusTzL5a+tZCFEJoi62BsHSVY/nHPudZVTKAg9+CEhGZIhhKPT89zqMcAEYtW026jNJ2gJ/uBiXYdKr8iRoZRkW7LlgKzljyEtjg6FPqh5JK7u7KwdFnYIqVd9pmshFb2d2JxhXAC9kIZWX615OSV5mNjQqyiunCsY3s8RdXpW7y8E37VZMXU7A73sCGP2JPerBr7u+yWgTVR95K9nvJ/eVwpQRA+aFevToAuN+MAgzWruHT7YIPgf6+ZM1gI//ZdnFfGH57vBKvvHPkOe3KUEIVjEk+fZ4vS/D5ZRK8ERx7eL1Dsm98hM6nfy8+5zmJ/NhHcJEj32RiPW7WPGfg15pta9PrsTamVfrXFevdPBj2lcweEdvyEn5CZSbSyflcJHTxSB9e3g/rakDWLK6qHhKI9czvk7VmhjIxAFifLpK/DqzczTbxmZkofeo4q8qaG3+uuyCXF77JH5KZ/THQCBALAw5gleo5TmMA2FlDabmTLoCqgyepx237FQhbYvHaWvAXhVIoGUrenxJyb9dlbr+qlz1DJLKrT6+//OyGVM76FFg0Ph4hg8roa9kgyboQECh1/sIHjQwKQ6hfx4h5n6GSuLmEVQaQCCbCAm+s/GqUnx1Xsmy7hOS83MRE/UURAdpFgW9V/w/yZuaZwii7e2D3MoraQaIJMfa2fiyCrLSg==
  template:
    metadata:
      name: sealed-rabbitmq-auth
      namespace: shortner
