---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sealed-rabbitmq-auth
  namespace: shortner
spec:
  encryptedData:
    password: AgBBzWofNNlc3w19UnHbPWCWD2sxkgJ3hB7sef7Qs8sIHolvGDuPRtYyA+2NIy2O6wajTFNWDVpY9LjE7lZSflKe7PEbRLVc1fJ1oTHlmlNYCZH0MO0BzqQiDFc7pHxZbEg6LkFbIsvqRkN9cr/ct/GbGCBAl0EcGaAyKbuvX+d0wZ8WiJDo5SPHV+afglYX0xFpHXXioGXXIqXa68sYn91muLHTC+u6gp9X3dh5GlCkQz0F9V2Z2EJTj7I/VjBLJ/d1K5AB2YnrAb523a+y1jPorr0ouYMOga+z4OGiyIQZ0lmNvIlKAohOCg3K/U6jzLEKT2wsqTIu/MQxzOAkpR9g/R40HBbQJmdBc/FpuutQ0iRWsN0pNQ05LQPb1LU8gSLymuoX9h0MmskX8EcOveTHChETHToBkckAKFP4LzkaJGs85u+4WzOZmV6ZKeqyXvsKA5Whj5hCHsnC6/DFTQaq+yv0EwyRoPaWWehi8YBYXKcYyoHkDxR1FHHlMLv6AHkcnN8bpmIP0U32ysNxwxpzCWqID3CrTVUR5dNNMWn9OlyR3xbVHZVJZrHCEKyYibqZ2ERMbbXcEZBNFwnIW+2TwXe0B1rEWrOahlEWvOWbo/geEqt4OjMIC7WuCJKwOxf+4gLL+u7KsKdMAdBY5s0f7dJdApCsA0v6mronry52TYkg2PdpHbp2k5u5La6qNMksLq6LnsCam09KrA==
    username: AgDEg2KPNKLx1c7B0PZVzkoZ4G5uccOjTZYzW1NqTGqOpkjcY/YVx9l8FFU3lQzhLNJj4b628Xl9kirpNXYRgETt5AQl6fiYqqbbrLW8Y5Gg3ofSMF0l4vIyiJsbrgp8KtTWavzNCb3U7YRcvrl42H7yabDQartr9UTj97tO0BlpOlKQUx/ertkykmjyAgiaLfJO7Robh+yN/ak9BRMXV2ZIHAS9vMzE9iyQkyIXfa7quhVpbuvvlhyGLGbouBnENA7rAsOsZ4/U9AhgZ/aVNYLVzYBM+priDniukQKUjzcliwjfy2iz/UiIqMdfghPQyvNGoCOgEiAnppnu1ZZcmSszV02MDMdIsCRsKFSkTacbCfxy7WOJlczwYre7lP/yfryGaMm1RDBJhPIt0nRh0cpL3gZH4VK2SqJ+AVUXLdv1PEQKBnBxGOGAJ5Ve2uBoITZWaRH5xpo7mBUqxayF2cNqgyguxB1Ais0OEGXVgwOuV+ReRAm0zu/73xXBQWPPlvCRBEv7p3KGhFy+O8hHMb1MFETxhjmmnVSMV9yx29b58DyTl8s3Kc8FTlfmz1ChYTAuT6SPP3WCDOoPLnlWRBRGSnR7a6W6lXzNtR5dJ+/Cy7gUqGbNuo7ACpbJiFyuEMXe5fmSN/C+umSQWejv3FwOj+/JtGPsNQZ+gfAm5XfJbWCp6X5xH3ZWaGQPwfvI+fZ/+aE6+wrPFnEXTYkzeMwy+Q==
  template:
    metadata:
      name: sealed-rabbitmq-auth
      namespace: shortner
