---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sealed-rabbitmq-auth
  namespace: rabbitmq
spec:
  encryptedData:
    password: AgCTj13HrV9LvRyXambSzxobH79FgJ/fHGxg9P1fWJn7eAdUF4AejJFFM+bXDI8gnet5R+VH+vToomrz+XnJvao2LB8xxaPkuhQTHa7qJVLkAAuJKjPkJM62LN5z2KG2hrLKKels0Wxyo3f24NxcAqdnfz9YTmAZtj4DkG3Ut+beAxOJ7VncgAY1VGfeebNjh32/DkVbLXbIGs52+E8YIHXwyNzwjblDje3FS9ClGo/nan5diEH4lk9o7RWQS9WdFXrg+YGHWFnWugrO0nf3Owm5cjoCUOwg+bfwoaVRv+vpiQn9qJem2NbYgXB+QKOh7XlmYTjm/sWng55K7YLw7kfPBW8iJ0ggNjDTpkjvkChengVLutxRqn0lwI6itslzwcnasehyBeEI0had0h30SGK5YBYpW6FT3SVnJm2Zefro3IfuxzU55/9iuxebgkDK4+cjwaNKIb+KvAyPfDcQnK5keh0klZdtJ269PfahoOeLJjEQt8FN2XMCDKGX8m4OfaP3jzujIkaTNTV1PnYDSQU+221nZKl9bDHbbNJYO4PmHvEeUgyVUQJFN2ACwfoxgXcZIEgq/LvWrkK1Q+oy/D5qSE4CwTeRL5NR2IJCQoKXu8CYvp+/099V2dEdCHmwvrrCqtXW92CswHs+iwWS9ZAj8cwNqGsMYW2sL+F5ay/biHX5UgG12QEzKD5wRceeFr159ys5ywf7xTNfqQ==
    username: AgCwjFkvyO1zW2rsJR/Z0Ohh7YrgYzkx1P2OYHl/pu0GsVIka7VPEMU2DGT+aJAbqLxeiVFncOxzPLOxMofDw7LzMqHzQ0go83LVe1/EBdyfvjWhP5B4dXu4APtRDvUoUuD+ubkxdu7m8zxggEAZVb3ir8B1uzdyhZqIlSwREXjMELXBUHvB8apphODJ6Yl2ceuDWXJmLq4tKKMS5K1lPIFu+MuM9m23VkqIMvVofLm8GfEZzmFqkV4TFZkGL+fG1BRwhLv8RxoS7bDQo6P5DK1qaOMJESNORX16056nNctWiGc8gIJlC2iE9eGclFlIbVOwCfgrMh9N6FCr/iRDki6jvrezIfdAwn73I1XsoCc3gXfr/YV1b3Ps4rVxAHOJNYrjX9bckN+nHBHs5ocPaDl356DgnvaqfR2dbjnloMOVf3ldz2NalS02z99YsW/gYlpO3FTMVin0sWsstRXNHHhGGtlRRlK+phJndcviREG6houPVZDPjhjDiUxzXX5dEUQ0HQ4cu0SSajFbgtRMNA6NwJ2xpHdpiSXixKSJhTFwZADiyL6XW8ooqyBrvAjXxrrIpmgqmrTwV8b9PRTeHQ33QIXWqXsMB0WEKy+T7MBysnvGZpEKabx6QK6lHeH+sICmLp1QbXHhQs0VA6DjTE5p/wdO5Pvk2WIuJz/rYFpgVaQUewR00ejLQQXIoi8Fr8dbJPFq04Unow==
  template:
    metadata:
      name: sealed-rabbitmq-auth
      namespace: rabbitmq
