---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shorturl-converter-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    combined_env: AgBkiBmRoBvM0hmUWZTMESGnOZo1Vf0rggqn/0CZJ7Uwlo7DzljQo4ig+gUOTaIvO6XR0H2RjEWfZf70M8qreMp2PafKj0ct4ZMQxwcgmP+kWvCFX+PdhiCeyuoqMVifWjCG69FR2LVodU/VAnlyy+bnePKso4fT4PsKS92taRxNNt+kQVxbvTlqbxxNle11L98YhRaWTJ0FEEx6LlaFbpTG2QQW2wkKyN0+9cfgszAdEmqvEwfOTCTI+v3PzZ3DRtPmVPhtvXRpWC3TOtPmZ25FJGhJWWRvRmXA7h4GfUASGf19dFC9c4HChOzQ0inbkDxXMqszbP+MQ/Cb/L4yuTrscTATTOEV+7dfKx6d1TfNVSHz1dQZZS7If5WcAhc34DXpGuforPQFEMbkhvA7CAzhp3UxruditoqmAwKuxDgX1X29fL/BmUhqb/cOmVDJc0YWKHKP+ibxGYbLtWhTrTxgbaKr1q8pfdOxqJihnfmm/xTQvZr/koliX+ZUtXj4kUz1kOmIvtArmiVwKwxjcZYfDoUMzGndcXnRjhM8gxc77hP8T2PzFXilvwfxIbHQUO/6uCGc48VzuIBBObDoosbV7NDO13GGRfTNpl4E0H+bhUBNS+bwly/bEdOoVWNlLCSLF8KkebR7ZQKiGbHbLdSGFJKL7qUuHL6678gnmhZ5HjsfE7jvhTbv4YPKU3piE4BFUeJiALPWcUya3WiRqdmlwdaCLOV6Ro6r2HoUYk/LSMtxQKEb4nLfnj8c6ulUPZVfsuXlB+YpBcdMuEYRTiTUapK8XDvDfNpMaDI9IHLPMTriCDweedDatMZhQa2cEJI27ThBzDRrTE5jtzkgqQsQwJ9u621XZ38eVluYOvidkBHvllYUbhPuk7D1Gyt2faOWh087BiMXuy7AnOO0I9b2FW7jAJMl/750v7WS1oty3BHqgErjSrltnI1bjss0XjkuAEXkykooJ5oddIlzuGXIGaC4QaOgQfMky2pHapfIEfXDqkPaEchhsjftSB3UK5qkAAvGvuxn63KT4VBxde9AYOV/mEaNyPSb2oIrOJtLgYro09t40wG1F6IJGfLlyq3eQkXbt+qtE2TQJSrDTVj6DHa8l7uEvXuwThZvioPiUFuuJ1v9
  template:
    metadata:
      name: shorturl-converter-sealed-secret
      namespace: shortner
