---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shorturl-converter-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    combined_env: AgAXb+pZX3qbGECVyYXaHJA0cywfxx1+BSDnhnGiXamn2Tiav9a7RosbYEsESOoWEBKOLpAgnSGstEuY2ncaenZA+qIYkc1Igw2JIxB053UveHOFZXkiljuwBhaD6z9HHu+eSwRTRa8UNiCn/yCsuZZkTZPFSJUqLogqY0MGES2kuoXDhs2V0SO3kk5Z3KfnMR7zms9YBiyZBzWLR4tGnlT+ncbehPuKOp3H0tqcwkTL0YJKWl0jj8AO6ZAY/TviK139XeBXLqitaJHIXHOmvJubUHDUxR5v+cbxpoLnv7oRB3QeUABmaMshCUrv5GfYrEIVIp9JrjmYDIRgBgdq2uKbFoeOAdV7n2BSfWWH0KnamslBAZIujw+0HlrRE6aIGApi1fdNnmgusJbiv3NNOLv4DwIVFeGIYVWdetlfUoMHeJ1+ahf199HBz0D+LRaMnRFUExAI4+QxSIo/6w+XKLu9NYVOgjPosLb2gxL30E9dOU1M7SqH2kxIiMdMo2zzdjzZ+FD5Rzm/+ZLX6X1pFfmipF0RTJw+bEV4pVGfUYlX0sOYHIptGEkepszzBFP/driBnZSGV40LdiYai/4v1es/U8nrGHIL3Y22bj4Kr/2PKCal0o/pMO5JJ8NhpW2Q/PjwQQGzNthoAvK13HiT3yo0iE4RdtBtZcVHvAHuosge6iRaxbkD3CxLkHI0OHbT1CgxcNWbPZM4y4QAvqG99EhKG1X+T1Sg+Vha3EbkroA7KwG+b7q+qw8n6QMVzPDPLXnHdfWJVmlONJvCdEgD/ZYBbHNLsBLRSkpThV3nEeRuCfMGkekKhQWq8NtWUOSVRS6Tc/qHpfT5xpv2SmKDoLTXegt9FUY92FUQhhyF/L39l9Exhheg18FeVnQihE5He7Nx5WMvGrH79UVl8agyIWAmykfSbSHfM4KGh7N59QVVpccpdJmlwBfKGB7b1/aP29xvuss+OerIp03Dfw6PTc8ExYwoFmCS37sQCRBlkrLdoXJptnA5fLVRRSSUEZJNf6VnxnTU9TYdBVbrqRkNK64vIkEcnX9ezhReiMVKlVnwBOFAiO7Ux71+d63bhVgTcVodKSj3xL0YYoKH364AbuSFWQDGnECpt902bubYM+IY76TJN++H
  template:
    metadata:
      name: shorturl-converter-sealed-secret
      namespace: shortner
