---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shorturl-converter-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    combined_env: AgCfFr8P2eiVhpfOqhfIq+LTlFgXomLfotjw/9OzWpLBHU/C8B/zdONb5SSXs9msAD9wyoaPiV2dNO5gcJrE1k1DVmqk9flarmH8Lr/v9j/Q4Vf90oUnsXZ79+hY/zi/AYI/wLHyZgxiAn3AQjGAJCtuVzDuql0rWEOTGU2lDTiuw0cI69Tn8cbYTTFOo/LP3wHkk/jx7d6ONFE3lHRoI/z84Ii/uT5trTj0eRs1n7P5ChbqFhU4W3LI8H7patwAGGlRapZTqo/BZaw8CxxmcFu6u3W8xhrUCsItWoh1hqta1wkIln91HTG0DCoTsN2lPFeXfzbj/vx6NeIGi/EpCMokNhhgOAdm5f/f8Pwxsy6Sl2LDHsLqWW6NEXIWasoEzetVCrPh2ZDeSmFcbm0vU8tSvYxB0WXzJ+JhKcMVAvHg28jCMRx3hvdY/bbOz27bQ5COIFnep+xrQxwdSad0c2yqTTaRF32syKnlwhyKlc493PMAxK3tFgvIHipF5O7PdHMRnfmvVGP/ozIAob5qeIUJyHG+B1Cv1C4d8Kef3GJO9JL2a8fYY2EebYIr2CcQWKrJytJodjuio6iS/yQY6Ocd4L6dwf/ZV4WTF83UwQ9l8Svk2peD9rs6yq5XD8Xm99OzPyIkTc5Fi5cwe0iEKnwC8u2LFys+87mT4+YTHqOSLLX5EUACs4cyzwmry9b5IVxaNI6srnF1Ht91nya1SHbB2GcemqQ1dzG5KiFGlZTxh7K1NZQ/wObIK89H3iGHvp8qHyqSZuvooJmrhvHfUzP/9MEBkzcBU38+NbRUyxr5lq5VkCyziwzWm+AOevVW1qAxGsl6sx1pXlKIzTkhgS7gfUNXyU7XBhrcP+/J7vug0VimBga9SD46Kes5ZU4yRo761CNZVczDdhHsTsbivc0j3b0Vftp+nTD6YqbOTnuOTO4zsnlSsxcBn+RjD4CXhpbWfrk2SPBpq8jRkzQNVotk1XcX+Z3nU8gL2VjYbdr2yrVkp4nWwtQnO8RYbCgzmb0h1yiZqzEOl6GK8VdoMj5cmtRiL7Rg5BxZHqNfJB3+366+DfegysfiQdfaTSG7J9wRJKlQy09C+Crz8qsuuxx9DP+unCaXloJnTFB6fV2wq5fpwG5+
  template:
    metadata:
      name: shorturl-converter-sealed-secret
      namespace: shortner
