---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ws-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    combined_env: AgB5bqpkgXCOoJ01pbxGMDZxS79isnI3dlUcw8XK+IN/EJsfhgUiFQ4JR41sOKftTAgl8DeFwdAxMQkBQKA4nW8wjtjvTLT9Xbki3cP7AIFSCZ7mtsSyB1x6FRpSBLC8Wj2AxHjr4yG6WAkD4Hnz/Gz1qeJ9VbDSEMzB95Qpk4MCn8T0UICVUkDOHvdBGqHdUXoHkHNh8oEaZtz1XfuUOrf9tOUHvKsCbvbObS/VouBnS6PU0NFG23TSW8k7UEIMUPmKHuXGTrZFAMHP5E9ia0ulBlrgVSzpihp9ehEiNMAjh/hX4277s+He7rNQojEXCIQT8ptibbF7YdgnUQOr6oMMn48HQnWV5Dq7qSsvvrmqTKOQe63cI6YyizyU3vFuRTa1F+psf6T2WQ+d4khXWIM7S0hUv8MRRn+NECs6Q+D0NNEt4l6Jwsv1XOHhXwXHqmenGTTe31NBHhKj0bJ8qSu39qp3U3JIc1Jx7S35kf6r4/ZSLSryn1MUy8UMW3Y7AnrvLnbOVBQidvgox55dEYhAazuQ3kYJDaYCAKADrVQqqw0qeLaUBNKokqU4BnBIUBzpVUHgXQ5MkCc7u+UeAaPL8LLpixJLiql5dNvLlLhMNn4oDsXdjrrW54Xv8n5jPdtgRGCcpsLdi9XkYRwyn9OXPXl2XRqCTMsyQTIgJVXHnh5zYOCVX5YwdsomFSbfPWybf7sYhopQocAzQ7YrVZrvwuuEsRJqfx/U73Qm8PpEm2iVAKXWfGv2cGyrxeuxAiB9aEJuROF5MgTX9xdJz2zbscCI4xcaEMrU
  template:
    metadata:
      name: ws-sealed-secret
      namespace: shortner
