---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ws-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    combined_env: AgBdK0ZrApuS7L4DkSTY8w55RFKlrgXQ2KFFW6HISJt1lyQvZY5D6o8nwQWoQL8E6abvMGEl4yKHkAB8tNqhEHl3NaQLMKj+kwiwMWLI4pyqVMQSAmCyLIJPNW6Q8T0cbqlxWVAS/ala1mPTvcDH0B7GZWix/vwZ/zTv7LxLm9Fh6SrhEzgFsnDaCHCcY+vXiRzjVjoUQ2+gJw4Q7SUF1w+MMC2TOY2u18MpaCFqtzyv6GV74crWdC7aY/1Prrpylb8JFMCC3aaap5cDaAwkfXozvTu8q48S9u4K93v8qBAEmNFRclGcMZ5iZXg4OPQ40HRuz12V+PrEytJ9dj3nsrerB5xveMEUKgY6I1GFNB1dhikZH6i+Da+yvDi8ccqL4GfEYYUFXsW9Cq2BtxPullAnMDL70GwNvKBT/dtve/EDUJ9WblwxPko1leNeXf+Bd7MX0XFYL6OTgpS8gydoXA1eiDKaAfeqspjF0tSyOQE8v144PmU8nCcKcFUJzpI2Mzuw1p+4dYxoCIH85+J5t4j+F89/bCcF50bMD85m19F+6GC2RcGHkOpEe0YLBWLoJ98Q08yj70Kbbkm7s5vWOoI2mLI13exhwcnBDsWZ30kBAoMODLBN4u6NUnhnv8cRas3jeekQ68iN9XTI6hFCOO7IOKuOd78WuMhWv9uRgpwEP9dt4os5wPZlIsaUmAVDMLg+TRASL/VsbmrFUcilnLXnRs8ThmibPI5jqbIbESwaYDsOq2np+HbLrM+6OMuxDzvGHMuu139OuYxx786NTzLHOeLdeZh3jOMY
  template:
    metadata:
      name: ws-sealed-secret
      namespace: shortner
