---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ws-sealed-secret
  namespace: shortner
spec:
  encryptedData:
    combined_env: AgDkbeaSfixlKUt/IZrERBMM3jcmRTcUfJmA0Qbqh81g6TvRv5ScGTVX2xPtggBOR98kPZadU5sLftyvMg8q7UfeeMn5kg5Ihkohq3UB/q2XF4Yw2+wvp/1LSn2PlSSn4/uGW6MFUCITgdBGj7nYVxU8yNN/pnQMhiE0NenTNhmlMa/miKxYL+D7hwT4snQuio/I5R1xclOeZJMK5DF4xCpIdXLCLLoYvD72A61TpNgtTR4JjenI1xvACQnhuxng1mXKglwUsK/6rwtgm9VjObkiNDlnp/Y3E974gS6gKhQ2zBAeAHKMe1ttFzKQR6zuMDJV++lew3gvdwP30+q5HACrmRqXptxLByyAWEgwQ+zfS2duiAD77jzz7zGHPihrCZNyhiprP/UxnqqZroyp9MXzTXNBWZpZ1Gdnw7zsM6j6lbNwRl5hklVeMw36W/2j/Mpm0GkuNtahJ7DVO25yMeDSm1iWzl5MSi8vCdIAmlKPLal7K/Znab9hZxGp5ISQGzR0nV8DePVa4Hjn6Qji55ENtI8TN+cWiqqlljeMzHaZJI5EwUwOemx2uhICfqp0J6bgZ/5Safcx3QaLmCvqkbYC1etMm5W+s91DKpLU6hXradfLN7XYVyYplxJMIfGnbbYHT02w6BWuGO/3kLBHhrCdDBJ7guaQvpzfw/bQhbNH8QVk4zwJO9+nav8/k5+3TLAGyc7dj/RrhFgiKeKpQ1UEhdfbOp7PLjvo/qJ7dW+qPay+j6SgWdxbxagsGIq+Bo/LDV+zCfo7h2kD0NJN3FXEaOmGsA9AO/FH
  template:
    metadata:
      name: ws-sealed-secret
      namespace: shortner
